<?php
/**
 * @file
 *   install file for commerce_migrate_ubercart.
 */

/**
 * Implements hook_uninstall() to deregister migrations.
 */
function commerce_migrate_ubercart_uninstall() {
  $migrations = array(
    'CommerceMigrateUbercartCustomerBillingProfile',
    'CommerceMigrateUbercartLineItem',
    'CommerceMigrateUbercartOrder',
    'CommerceMigrateUbercartLineItem',
    'CommerceMigrateUbercartNode',
    'CommerceMigrateUbercartProductType',
  );
  module_load_include('module', 'commerce_migrate_ubercart');
  module_load_include('inc', 'commerce_migrate_ubercart', 'product');
  module_load_include('inc', 'commerce_migrate_ubercart', 'customer_billing_profile');
  module_load_include('inc', 'commerce_migrate_ubercart', 'line_item');
  module_load_include('inc', 'commerce_migrate_ubercart', 'order');
  module_load_include('inc', 'commerce_migrate_ubercart', 'product_node');
  module_load_include('inc', 'commerce_migrate_ubercart', 'product_type');
  $migrations = array_merge(
    $migrations,
    CommerceMigrateUbercartProductMigration::getProductMigrations(),
    CommerceMigrateUbercartNodeMigration::getProductNodeMigrations()
  );
  foreach ($migrations as $migration) {
    Migration::deregisterMigration($migration);
  }

  // Get rid of old variables.
  $variables = array(
    'commerce_migrate_ubercart_source_database_api_version',
    'commerce_migrate_ubercart_source_database',
    'commerce_migrate_ubercart_source_database_api_version',
    'commerce_migrate_ubercart_public_files_directory',
    'commerce_migrate_ubercart_source_drupal_root',
    'commerce_migrate_ubercart_default_filter_format',
    'commerce_migrate_ubercart_user_map_ok',
    'commerce_migrate_ubercart_user_migration_class',
    'commerce_migrate_ubercart_image_fields'
  );
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
